#! /bin/bash
echo ""
echo -e "\e[1;32m========\e[0m\e[1;31mCARDING\e[0m\e[1;32m========\e[0m"
echo ""
echo -e -n "\e[1;34m[#]Escribe un puerto >>\e[0m \e[1;37m\e[0m"                         
read puerto
echo ""                                                                                 
setterm -foreground red                                                                 
echo "# Iniciando localhost al puerto $puerto ..."
echo ""
sleep 2                                                                                 
setterm -foreground green
echo "---------------------------------"
setterm -foreground cyan
echo "Copie el link, peguelo en google"
echo "Link = http://localhost:$puerto"                                                  
setterm -foreground green
echo "---------------------------------"
echo ""
cd Pagina-de-Carding
php -S 0.0.0.0:$puerto
