#!/bin/bash
clear

echo -e "        \e[1;31m┈┈┈┈╱▔▔▔▔╲┈┈┈┈\e[0m"
echo -e "        \e[1;31m┈┈┈▕\e[0m\e[1;37m▕╲\e[0m\e[1;31m┊┊\e[0m\e[1;37m╱▏\e[0m\e[1;31m▏┈┈┈\e[0m"
echo -e "        \e[1;31m┈┈┈▕\e[0m\e[1;37m▕▂╱╲▂▏\e[1;31m▏┈┈┈\e[0m"
echo -e "        \e[1;31m┈┈┈┈╲┊┊┊┊╱┈┈┈┈\e[0m"
echo -e "        \e[1;31m┈┈┈┈▕╲▂▂╱▏┈┈┈┈\e[0m"
echo -e "        \e[1;31m╱▔▔▔▔┊┊┊┊▔▔▔▔╲\e[0m"

amarillo="\033[1;33m"
blanco="\033[1;37m"
rojo="\033[1;31m"
cyan="\033[1;36m"

echo " "
echo -e "        \e[1;33m%%%%%\e[0m\e[1;34m%%%%%\e[0m\e[1;31m%%%%%\e[0m"
echo -e "          \e[1;31mCode:\e[0m \e[1;37mD€mO ♤\e[0m"
echo -e "          \e[1;31mVersión:\e[0m \e[1;37m1.6\e[0m"
echo -e "        \e[1;33m%%%%%\e[0m\e[1;34m%%%%%\e[0m\e[1;31m%%%%%\e[0m"
echo -e "$rojo---------------------------------"
echo -e "\e[1;37m[\e[0m\e[1;31m#\e[0m\e[1;37m]\e[0m \e[1;33mEscribe la CC a extrapolar\e[0m " 
read -p "CC: " Extrapolacion
echo -e "$rojo---------------------------------"
echo -e $blanco" "
echo -e "$cyan----> $blanco${Extrapolacion:0:12}xxxx "
echo -e "$cyan----> $blanco${Extrapolacion:0:11}xxxxx "
echo -e "$cyan----> $blanco${Extrapolacion:0:8}xxxx${Extrapolacion:12:1}x${Extrapolacion:14:16} "
echo -e "$cyan----> $blanco${Extrapolacion:0:10}xxxxxx "
echo -e "$cyan----> $blanco${Extrapolacion:0:6}x${Extrapolacion:7:1}x${Extrapolacion:9:1}x${Extrapolacion:11:1}x${Extrapolacion:13:1}x${Extrapolacion:15:1} "
echo ""
python datecc.py
while :
do 
echo ""
echo -e "\e[1;32mDesea continuar usando el programa\e[0m \e[1;37msi/no\e[0m"
echo -e -n "\e[1;37m>>> \e[0m"
read menu
case $menu in
si)
#! /bin/bash
python scream.py
exit
;;
no)
#! /bin/bash
echo -e "\e[1;37m[+]\e[0m \e[1;32mSCREAM BIN ,BYE\e[0m"
sleep 1
exit
;;
esac
done
